-- =============================================================================
-- 03_roles.sql
-- Implements a least-privilege RBAC model.
-- Roles follow the Snowflake recommended pattern:
--   Functional Roles (what you DO) grant to Access Roles (what you SEE).
--
-- Hierarchy:
--
--   ACCOUNTADMIN
--   ├── SECURITYADMIN
--   │   └── USERADMIN
--   └── SYSADMIN
--       ├── LOADER_ROLE           (ingestion service accounts)
--       ├── TRANSFORMER_ROLE      (dbt service account)
--       ├── DATA_ENGINEER_ROLE    (platform engineers)
--       ├── DATA_ANALYST_ROLE     (business analysts — read silver + gold)
--       ├── DATA_SCIENTIST_ROLE   (ML/DS team)
--       └── POWERBI_ROLE          (Power BI gateway service account)
--           ├── POWERBI_MARKETING_ROLE   (AD group: PBI_MARKETING)
--           └── POWERBI_FINANCE_ROLE     (AD group: PBI_FINANCE)
--
-- Run as: SECURITYADMIN
-- =============================================================================

USE ROLE SECURITYADMIN;

-- ---------------------------------------------------------------------------
-- FUNCTIONAL ROLES — assigned to humans and service accounts
-- ---------------------------------------------------------------------------

CREATE ROLE IF NOT EXISTS LOADER_ROLE
    COMMENT = 'Ingestion service accounts (Fivetran, ADF, Snowpipe). Write to RAW_DB only.';

CREATE ROLE IF NOT EXISTS TRANSFORMER_ROLE
    COMMENT = 'dbt service account. Read RAW_DB; write FOUNDATION_DB and ANALYTICS_DB.';

CREATE ROLE IF NOT EXISTS DATA_ENGINEER_ROLE
    COMMENT = 'Platform engineers. Full read across all layers; DDL on DEV_DB.';

CREATE ROLE IF NOT EXISTS DATA_ANALYST_ROLE
    COMMENT = 'Business analysts. Read ANALYTICS_DB (gold) and FOUNDATION_DB (silver).';

CREATE ROLE IF NOT EXISTS DATA_SCIENTIST_ROLE
    COMMENT = 'ML / data science team. Read all layers; create objects in DEV_DB.';

CREATE ROLE IF NOT EXISTS POWERBI_ROLE
    COMMENT = 'Power BI gateway service account. Read ANALYTICS_DB. RLS enforced.';

-- Domain-scoped Power BI roles (mapped from Azure AD groups via SAML)
CREATE ROLE IF NOT EXISTS POWERBI_MARKETING_ROLE
    COMMENT = 'Power BI users in AD group PBI_MARKETING. RLS filters to marketing data.';

CREATE ROLE IF NOT EXISTS POWERBI_FINANCE_ROLE
    COMMENT = 'Power BI users in AD group PBI_FINANCE. RLS filters to finance data.';

CREATE ROLE IF NOT EXISTS POWERBI_OPERATIONS_ROLE
    COMMENT = 'Power BI users in AD group PBI_OPERATIONS. RLS filters to operations data.';

-- ---------------------------------------------------------------------------
-- ROLE HIERARCHY
-- All custom roles must roll up to SYSADMIN so admins retain access.
-- ---------------------------------------------------------------------------

GRANT ROLE LOADER_ROLE              TO ROLE SYSADMIN;
GRANT ROLE TRANSFORMER_ROLE         TO ROLE SYSADMIN;
GRANT ROLE DATA_ENGINEER_ROLE       TO ROLE SYSADMIN;
GRANT ROLE DATA_ANALYST_ROLE        TO ROLE DATA_ENGINEER_ROLE;
GRANT ROLE DATA_SCIENTIST_ROLE      TO ROLE DATA_ENGINEER_ROLE;
GRANT ROLE POWERBI_ROLE             TO ROLE SYSADMIN;
GRANT ROLE POWERBI_MARKETING_ROLE   TO ROLE POWERBI_ROLE;
GRANT ROLE POWERBI_FINANCE_ROLE     TO ROLE POWERBI_ROLE;
GRANT ROLE POWERBI_OPERATIONS_ROLE  TO ROLE POWERBI_ROLE;

-- ---------------------------------------------------------------------------
-- WAREHOUSE GRANTS
-- ---------------------------------------------------------------------------

GRANT USAGE ON WAREHOUSE INGESTION_WH    TO ROLE LOADER_ROLE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH    TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH    TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH   TO ROLE DATA_ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH   TO ROLE POWERBI_ROLE;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH   TO ROLE POWERBI_MARKETING_ROLE;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH   TO ROLE POWERBI_FINANCE_ROLE;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH   TO ROLE POWERBI_OPERATIONS_ROLE;
GRANT USAGE ON WAREHOUSE DATASCIENCE_WH TO ROLE DATA_SCIENTIST_ROLE;
GRANT USAGE ON WAREHOUSE ADMIN_WH       TO ROLE DATA_ENGINEER_ROLE;

-- ---------------------------------------------------------------------------
-- DATABASE GRANTS: RAW_DB (Bronze)
-- ---------------------------------------------------------------------------

-- LOADER_ROLE: write access to all raw schemas
GRANT USAGE ON DATABASE RAW_DB TO ROLE LOADER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW_DB TO ROLE LOADER_ROLE;
GRANT CREATE TABLE, CREATE STAGE, CREATE PIPE
    ON ALL SCHEMAS IN DATABASE RAW_DB TO ROLE LOADER_ROLE;
GRANT INSERT, UPDATE ON ALL TABLES IN DATABASE RAW_DB TO ROLE LOADER_ROLE;

-- TRANSFORMER_ROLE: read-only access to raw landing schemas (source for dbt),
-- plus DDL on the dedicated BRONZE schema where dbt materialises bronze views.
GRANT USAGE ON DATABASE RAW_DB TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW_DB TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE RAW_DB TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW_DB TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE RAW_DB TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE RAW_DB TO ROLE TRANSFORMER_ROLE;
GRANT CREATE VIEW ON SCHEMA RAW_DB.BRONZE TO ROLE TRANSFORMER_ROLE;

-- DATA_ENGINEER_ROLE: read all raw schemas (tables and bronze views)
GRANT USAGE ON DATABASE RAW_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE RAW_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE RAW_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE RAW_DB TO ROLE DATA_ENGINEER_ROLE;

-- DATA_SCIENTIST_ROLE: read all raw schemas (role comment promises "read all layers")
GRANT USAGE ON DATABASE RAW_DB TO ROLE DATA_SCIENTIST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW_DB TO ROLE DATA_SCIENTIST_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE RAW_DB TO ROLE DATA_SCIENTIST_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW_DB TO ROLE DATA_SCIENTIST_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE RAW_DB TO ROLE DATA_SCIENTIST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE RAW_DB TO ROLE DATA_SCIENTIST_ROLE;

-- ---------------------------------------------------------------------------
-- DATABASE GRANTS: FOUNDATION_DB (Silver)
-- ---------------------------------------------------------------------------

-- TRANSFORMER_ROLE: full DDL + DML (dbt creates/replaces models here)
GRANT USAGE ON DATABASE FOUNDATION_DB TO ROLE TRANSFORMER_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE FOUNDATION_DB TO ROLE TRANSFORMER_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE FOUNDATION_DB TO ROLE TRANSFORMER_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE FOUNDATION_DB TO ROLE TRANSFORMER_ROLE;
GRANT CREATE SCHEMA ON DATABASE FOUNDATION_DB TO ROLE TRANSFORMER_ROLE;

-- DATA_ENGINEER_ROLE: read silver
GRANT USAGE ON DATABASE FOUNDATION_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FOUNDATION_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE FOUNDATION_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE FOUNDATION_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE FOUNDATION_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE FOUNDATION_DB TO ROLE DATA_ENGINEER_ROLE;

-- DATA_ANALYST_ROLE: read silver
GRANT USAGE ON DATABASE FOUNDATION_DB TO ROLE DATA_ANALYST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FOUNDATION_DB TO ROLE DATA_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE FOUNDATION_DB TO ROLE DATA_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE FOUNDATION_DB TO ROLE DATA_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE FOUNDATION_DB TO ROLE DATA_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE FOUNDATION_DB TO ROLE DATA_ANALYST_ROLE;

-- DATA_SCIENTIST_ROLE: read silver
GRANT USAGE ON DATABASE FOUNDATION_DB TO ROLE DATA_SCIENTIST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FOUNDATION_DB TO ROLE DATA_SCIENTIST_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE FOUNDATION_DB TO ROLE DATA_SCIENTIST_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE FOUNDATION_DB TO ROLE DATA_SCIENTIST_ROLE;

-- ---------------------------------------------------------------------------
-- DATABASE GRANTS: ANALYTICS_DB (Gold)
-- ---------------------------------------------------------------------------

-- TRANSFORMER_ROLE: full DDL + DML
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE TRANSFORMER_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ANALYTICS_DB TO ROLE TRANSFORMER_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE ANALYTICS_DB TO ROLE TRANSFORMER_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE ANALYTICS_DB TO ROLE TRANSFORMER_ROLE;
GRANT CREATE SCHEMA ON DATABASE ANALYTICS_DB TO ROLE TRANSFORMER_ROLE;

-- DATA_ANALYST_ROLE: read gold
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE DATA_ANALYST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS_DB TO ROLE DATA_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS_DB TO ROLE DATA_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE ANALYTICS_DB TO ROLE DATA_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE ANALYTICS_DB TO ROLE DATA_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE ANALYTICS_DB TO ROLE DATA_ANALYST_ROLE;

-- DATA_SCIENTIST_ROLE: read gold
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE DATA_SCIENTIST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS_DB TO ROLE DATA_SCIENTIST_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS_DB TO ROLE DATA_SCIENTIST_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE ANALYTICS_DB TO ROLE DATA_SCIENTIST_ROLE;

-- POWERBI domain roles: read only on domain-specific schemas
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE POWERBI_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS_DB TO ROLE POWERBI_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS_DB TO ROLE POWERBI_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE ANALYTICS_DB TO ROLE POWERBI_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE ANALYTICS_DB TO ROLE POWERBI_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE ANALYTICS_DB TO ROLE POWERBI_ROLE;

-- Marketing schema only
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE POWERBI_MARKETING_ROLE;
GRANT USAGE ON SCHEMA ANALYTICS_DB.MARKETING TO ROLE POWERBI_MARKETING_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_DB.MARKETING TO ROLE POWERBI_MARKETING_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.MARKETING TO ROLE POWERBI_MARKETING_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS_DB.MARKETING TO ROLE POWERBI_MARKETING_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.MARKETING TO ROLE POWERBI_MARKETING_ROLE;

-- Finance schema only
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE POWERBI_FINANCE_ROLE;
GRANT USAGE ON SCHEMA ANALYTICS_DB.FINANCE TO ROLE POWERBI_FINANCE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_DB.FINANCE TO ROLE POWERBI_FINANCE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.FINANCE TO ROLE POWERBI_FINANCE_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS_DB.FINANCE TO ROLE POWERBI_FINANCE_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DB.FINANCE TO ROLE POWERBI_FINANCE_ROLE;

-- Operations schema only
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE POWERBI_OPERATIONS_ROLE;
GRANT USAGE ON SCHEMA ANALYTICS_DB.OPERATIONS TO ROLE POWERBI_OPERATIONS_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_DB.OPERATIONS TO ROLE POWERBI_OPERATIONS_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB.OPERATIONS TO ROLE POWERBI_OPERATIONS_ROLE;

-- ---------------------------------------------------------------------------
-- DATABASE GRANTS: MONITORING_DB
-- ---------------------------------------------------------------------------

GRANT USAGE ON DATABASE MONITORING_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE MONITORING_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE MONITORING_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE MONITORING_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE MONITORING_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE MONITORING_DB TO ROLE DATA_ENGINEER_ROLE;

-- TRANSFORMER_ROLE: write data quality results.
-- CREATE TABLE is required because dbt's store_failures materialises failed
-- test rows as tables in this schema (see dbt_project.yml data_tests config).
GRANT USAGE ON DATABASE MONITORING_DB TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON SCHEMA MONITORING_DB.DATA_QUALITY TO ROLE TRANSFORMER_ROLE;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA MONITORING_DB.DATA_QUALITY TO ROLE TRANSFORMER_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA MONITORING_DB.DATA_QUALITY TO ROLE TRANSFORMER_ROLE;

-- Elementary observability package writes its artefact models here (see
-- dbt_project.yml `elementary` model config)
GRANT USAGE ON SCHEMA MONITORING_DB.ELEMENTARY TO ROLE TRANSFORMER_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA MONITORING_DB.ELEMENTARY TO ROLE TRANSFORMER_ROLE;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA MONITORING_DB.ELEMENTARY TO ROLE TRANSFORMER_ROLE;

-- ---------------------------------------------------------------------------
-- DEV_DB: developers can create their own schemas
-- ---------------------------------------------------------------------------

GRANT USAGE ON DATABASE DEV_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON DATABASE DEV_DB TO ROLE DATA_SCIENTIST_ROLE;
GRANT CREATE SCHEMA ON DATABASE DEV_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT CREATE SCHEMA ON DATABASE DEV_DB TO ROLE DATA_SCIENTIST_ROLE;

-- ---------------------------------------------------------------------------
-- TEST_DB: ephemeral CI runs (dbt ci target builds all layers here)
-- ---------------------------------------------------------------------------

GRANT USAGE ON DATABASE TEST_DB TO ROLE TRANSFORMER_ROLE;
GRANT CREATE SCHEMA ON DATABASE TEST_DB TO ROLE TRANSFORMER_ROLE;
